import { sections } from '../data/inquiryGuide'
import { redFlags } from '../data/redFlags'
import { rubricDimensions, MAX_RUBRIC_SCORE } from '../data/rubric'
import { scorecardDomains } from '../data/scorecard'

interface ExportData {
  meta: { customerName: string; useCaseName: string; date: string; fde: string; useCaseSummary: string }
  answers: Record<string, string>
  triggeredFlags: string[]
  rubricScores: Record<string, number>
  scorecardScores: Record<string, number>
  scorecardNotes: Record<string, string>
  verdict: string
  verdictRaw: string
}

function getTier(score: number): string {
  if (score <= 7) return 'Below Baseline'
  if (score <= 14) return 'Baseline'
  if (score <= 20) return 'Strong'
  return 'Elite'
}

export function generateMarkdown(data: ExportData): string {
  const { meta, answers, triggeredFlags, rubricScores, scorecardScores, scorecardNotes, verdictRaw } = data
  const lines: string[] = []

  const title = [meta.customerName, meta.useCaseName].filter(Boolean).join(' — ') || 'Discovery'
  lines.push(`# FDE Agent Discovery — ${title}`)
  lines.push(``)
  lines.push(`> **Customer:** ${meta.customerName || 'N/A'}  `)
  lines.push(`> **Use Case:** ${meta.useCaseName || 'N/A'}  `)
  lines.push(`> **Date:** ${meta.date}  `)
  lines.push(`> **FDE:** ${meta.fde || 'N/A'}  `)
  lines.push(``)
  if (meta.useCaseSummary) {
    lines.push(`### Use Case Summary`)
    lines.push(``)
    lines.push(meta.useCaseSummary)
    lines.push(``)
  }
  lines.push(``)
  lines.push(`---`)
  lines.push(``)

  // Discovery sections
  lines.push(`## Discovery Questionnaire`)
  lines.push(``)
  for (const section of sections) {
    lines.push(`### ${section.label}`)
    lines.push(`*${section.goal}*`)
    lines.push(``)
    for (const q of section.questions) {
      const answer = answers[q.id] || '_No answer recorded_'
      lines.push(`**${q.id} — ${q.question}**`)
      lines.push(``)
      lines.push(answer)
      lines.push(``)
    }
  }

  lines.push(`---`)
  lines.push(``)

  // Red flags
  const triggered = redFlags.filter(f => triggeredFlags.includes(f.id))
  lines.push(`## Red Flag Checklist`)
  lines.push(``)
  lines.push(`**${triggered.length} of 22 flags triggered**`)
  lines.push(``)
  if (triggered.length > 0) {
    for (const f of triggered) {
      lines.push(`- 🚩 **[${f.severity.toUpperCase()}]** ${f.flag}`)
      lines.push(`  - *Translation: ${f.translation}*`)
    }
  } else {
    lines.push(`_No red flags triggered._`)
  }
  lines.push(``)
  lines.push(`---`)
  lines.push(``)

  // Rubric
  const totalScore = rubricDimensions.reduce((sum, d) => sum + (rubricScores[d.id] || 0) * d.weight, 0)
  const pct = Math.round((totalScore / MAX_RUBRIC_SCORE) * 100)
  lines.push(`## High Value / High Impact Rubric`)
  lines.push(``)
  lines.push(`**Total Score: ${totalScore} / ${MAX_RUBRIC_SCORE} (${pct}%)**`)
  lines.push(``)
  lines.push(`| Dimension | Score | Weight | Weighted |`)
  lines.push(`|---|---|---|---|`)
  for (const d of rubricDimensions) {
    const s = rubricScores[d.id] || 0
    lines.push(`| ${d.label} | ${s}/5 | ${d.weight}x | ${s * d.weight} |`)
  }
  lines.push(``)
  lines.push(`---`)
  lines.push(``)

  // Scorecard
  lines.push(`## FDE Agentic Scorecard`)
  lines.push(``)
  lines.push(`| Domain | Score | Tier |`)
  lines.push(`|---|---|---|`)
  for (const d of scorecardDomains) {
    const s = scorecardScores[d.id] || 0
    lines.push(`| ${d.shortLabel} | ${s}/25 | ${getTier(s)} |`)
  }
  lines.push(``)
  for (const d of scorecardDomains) {
    const note = scorecardNotes[d.id]
    if (note) {
      lines.push(`**${d.shortLabel} — Evidence:** ${note}`)
      lines.push(``)
    }
  }

  lines.push(`---`)
  lines.push(``)

  // AI Verdict
  if (verdictRaw) {
    lines.push(`## AI Verdict`)
    lines.push(``)
    lines.push(verdictRaw)
    lines.push(``)
  }

  lines.push(`---`)
  lines.push(``)
  lines.push(`*Generated by FDE Agent Discovery Dashboard*`)

  return lines.join('\n')
}

export function downloadMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
